### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by eryajf** [glidea/zenfeed#1]
1. 前端是否也开源了，感觉可以再做下封装，embed到后端里，就能简化一些部署。
2. 部署命令略微有点点抽象，建议可直接引导用docker-compose.yaml，我把配置合并了下：

```
services:
  zenfeed:
    image: glidea/zenfeed:latest
    configs:
      - source: zenfeed_config
        target: /app/config/config.yaml
    volumes:
      - data:/app/data
    ports:
      - "1300:1300"
      - "1301:1301"
    depends_on:
      - rsshub

  rsshub:
    image: diygod/rsshub:latest
    ports:
      - "1200:1200"
    environment:
      - NODE_ENV=production
      
volumes:
  data: {}

configs:
  zenfeed_config:
    content: |
      timezone: Asia/Shanghai
      llms:
        - name: general
          default: true
          provider: siliconflow
          model: Qwen/Qwen2.5-7B-Instruct
          api_key: "<API_KEY>"
        - name: embed
          provider: siliconflow
          embedding_model: Pro/BAAI/bge-m3
          api_key: "<API_KEY>"
      scrape:
        rsshub_endpoint: http://rsshub:1200
      storage:
        feed:
          rewrites:
            - transform:
                to_text:
                  prompt: |-
                    {{.summary_html_snippet}}使用中文回复
              label: summary_html_snippet
          embedding_llm: embed
      notify:
        channels:
          email:
            feed_html_snippet_template: |
              {{ .summary_html_snippet }}
```
