### ISSUE TITLE
求一下各位佬的配置文件参考，主要是storage、scheduls部分

### ISSUE THREAD

**Issue by artxia** [glidea/zenfeed#16]
目前这部分参考配置说明，但是配置出来的效果还是不理想。
另外 api.rss 配置 如果有更好啦
这是我的配置

```
storage:
    feed:
        rewrites:
            - skip_too_short_threshold: 0
              match_re: ^[\s\S]{0,300}$
              action: drop_feed
            - transform:
                to_text:
                    llm: general
                    prompt: |
                        {{ .summary_html_snippet }} Respond in Chinese. Keep the corresponding image and URL link. Generate HTML, TailwindCSS formatted output, minimalist style, big company aesthetics
              label: summary_html_snippet
            - transform:
                to_text:
                    llm: general
                    prompt: |
                        {{ .category }}
              label: category
            - transform:
                to_text:
                    llm: general
                    prompt: |
                        {{ .tags }} 使用中文回复
              label: tags
            - skip_too_short_threshold: 0
              transform:
                to_text:
                    llm: general
                    prompt: |
                        {{ .score }}
              label: score
            - source_label: score
              skip_too_short_threshold: 0
              match_re: ^[0-6]$
              action: drop_feed
            - source_label: title
              skip_too_short_threshold: 0
              transform:
                to_text:
                    llm: general
                    prompt: 'Respond in Chinese'
              label: title
        embedding_llm: embed
scheduls:
    rules:
        - name: AI每日新闻
          query: AI每日新闻汇总
          every_day: -12:00~12:00
        - name: 中美又有什么新鲜事
          query: 中美又有什么新鲜事
          every_day: -12:00~12:00
        - name: 俄乌战争又有新的进展
          query: 俄乌战争又有新的进展
          every_day: -12:00~12:00
```
