### ISSUE TITLE
ubuntu24 docker-compose 部署时报错

### ISSUE THREAD

**Issue by newhackerman** [glidea/zenfeed#5]
docker-compose -p zenfeed up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
configs.zenfeed_config_base value 'content' does not match any of the regexes: '^x-'

**Comment by glidea** [comment]
可以贴下你的 Compose yml 吗？


注意是：
```yaml
configs:
  zenfeed_config_base:
    content: |
      timezone: ${TZ:-Asia/Shanghai}
```

而不是
```yaml
configs:
  zenfeed_config_base:
    content:
      timezone: ${TZ:-Asia/Shanghai}
```
